From python:3.12-slim

WORKDIR /webscraper

COPY requirements.txt .
     

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8010

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]