services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '8000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  webscraper:
    build:
      context: ./webscraper
      dockerfile: Dockerfile 
    ports:
     - "8010:8000" 
    volumes:
     - ./app:/app 

volumes:
  grafana-storage: {}
   